### ISSUE TITLE
Bug in File Structure. 

### ISSUE THREAD

**Issue by raysandeep** [GDGVIT/go-template#1]
With this file structure, we can't achieve Many 2 Many Relationships. 
Since every single model belongs to a different package, which will result in circular import. 

For Eg: 
go-template/pkg/user.go will be:
```
import "github.com/gdgvit/go-template/pkg/groups"
type User struct {
    Groups         []Groups         `json:"groups,omitempty" gorm:"many2many:groups"`
}
```
go-template/pkg/group.go will be:
```
import "github.com/gdgvit/go-template/pkg/user"
type Group struct {
Users         []User         `json:"groups,omitempty" gorm:"many2many:groups"`
}
```

This will eventually end up with a circular import. 
Correct me if I'm wrong @L04DB4L4NC3R

**Comment by L04DB4L4NC3R** [comment]
Many to many relationships should either be handled in a common package which imports from both group and user, or entities with relationships should be defined in the same package.

**Comment by raysandeep** [comment]
If these two models are really heavy then it will clutter the whole package. Then I don't think it's a clean architecture

**Comment by L04DB4L4NC3R** [comment]
Each package can contain more than one file, so this will never be an issue.

**Comment by raysandeep** [comment]
Lol okay
